apiVersion: apps/v1
kind: Deployment
metadata:
  name: attestation
  namespace: lotabots
  labels:
    app: lotabots
    component: attestation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lotabots
      component: attestation
  template:
    metadata:
      labels:
        app: lotabots
        component: attestation
    spec:
      containers:
      - name: attestation
        image: ghcr.io/lotabots/attestation:IMAGE_TAG
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: lotabots-config
        - secretRef:
            name: lotabots-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: ghcr-secret 