apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lotabots

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- preprocessing-deployment.yaml
- training-deployment.yaml
- inference-deployment.yaml
- attestation-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: lotabots
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  contact: "team@lotabots.ai"
  environment: base

images:
- name: lotabots/preprocessing-service
  newTag: latest
- name: lotabots/training-service
  newTag: latest
- name: lotabots/inference-service
  newTag: latest
- name: lotabots/attestation-service
  newTag: latest

configMapGenerator:
- name: lotabots-config
  behavior: merge
  literals:
  - ENVIRONMENT=base

secretGenerator:
- name: lotabots-secrets
  behavior: merge
  files:
  - secrets/nvidia-attestation-api-key
  - secrets/wandb-api-key
  - secrets/mlflow-tracking-token
  - secrets/jwt-secret-key

replicas:
- name: preprocessing-service
  count: 2
- name: training-service
  count: 1
- name: inference-service
  count: 2
- name: attestation-service
  count: 2

patchesStrategicMerge:
- patches/resource-limits.yaml
- patches/hpa-settings.yaml
- patches/security-context.yaml 