---
version: '3.8'

services:
  api-gateway:
    image: rust:1.67-slim
    container_name: api-gateway
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    networks:
      - lotabots-network
    environment:
      - RUST_LOG=info
    volumes:
      - ./config:/config:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  inference-service:
    image: python:3.9-slim
    container_name: inference-service
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    networks:
      - lotabots-network
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/models:ro
    depends_on:
      api-gateway:
        condition: service_healthy

networks:
  lotabots-network:
    driver: bridge
