# Default configuration for the API Gateway

environment = "development"
host = "0.0.0.0"
port = 8080

[database]
url = "postgresql://localhost/lotabots"
max_connections = 20
idle_timeout_seconds = 300

[security]
jwt_secret = "REPLACE_THIS_WITH_A_SECURE_SECRET_IN_PRODUCTION"
token_expiry_hours = 24
refresh_token_expiry_days = 30
password_hash_iterations = 100000
minimum_password_length = 12

[rate_limit]
free_tier_rpm = 60
pro_tier_rpm = 300
enterprise_tier_rpm = 0  # 0 means unlimited
burst_multiplier = 1.5

[metrics]
prometheus_endpoint = "/metrics"
metrics_prefix = "lotabots_api"
collection_interval_seconds = 15

[logging]
level = "info"
format = "json"
output_path = "logs/api-gateway.log" 