apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: lotabots
data:
  config.hcl: |
    ui = true
    
    storage "raft" {
      path = "/vault/data"
      node_id = "node-1"
    }
    
    listener "tcp" {
      address = "[::]:8200"
      tls_disable = 1  # For development only, use proper TLS in production
    }
    
    api_addr = "http://vault.lotabots.svc:8200"
    cluster_addr = "https://vault.lotabots.svc:8201"
    
    service_registration "kubernetes" {} 