---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference-container
        image: <your-repo>/inference:latest
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8080  # If exposing an HTTP endpoint 