---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessing
  template:
    metadata:
      labels:
        app: preprocessing
    spec:
      containers:
      - name: preprocessing-container
        image: <your-repo>/preprocessing:latest
        resources:
          limits:
            nvidia.com/gpu: 1  # Request 1 GPU if needed
        env:
        - name: INPUT_DATA_PATH
          value: "/data/input.txt"
        - name: OUTPUT_DATA_PATH
          value: "/data/output.txt"
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        emptyDir: {}  # Or configure a persistent volume if needed 