[package]
name = "lotabots-config"
version = "0.1.0"
edition = "2021"
description = "Common configuration library for LotaBots services"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0" 