[package]
name = "lotabots-error"
version = "0.1.0"
edition = "2021"
description = "Shared error types and handling for LotaBots"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
actix-web = "4.4"
