[package]
name = "lotabots-config"
version = "0.1.0"
edition = "2021"
description = "Shared configuration management for LotaBots"

[dependencies]
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
tracing = "0.1"
thiserror = "1.0"
