---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lotabots
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'lotabots'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: lotabots
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: metrics

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: lotabots
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: lotabots
        const_labels:
          environment: production

      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, logging]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: lotabots
  labels:
    app: lotabots
    component: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lotabots
      component: otel-collector
  template:
    metadata:
      labels:
        app: lotabots
        component: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:0.70.0
        args:
          - "--config=/conf/otel-collector-config.yaml"
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 8889
          name: prometheus
        volumeMounts:
        - name: otel-collector-config
          mountPath: /conf
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: otel-collector-config
        configMap:
          name: otel-collector-config

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: lotabots
  labels:
    app: lotabots
    component: otel-collector
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  - name: prometheus
    port: 8889
    targetPort: 8889
  selector:
    app: lotabots
    component: otel-collector 