version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ..:/usr/src/app:cached
      - cargo-cache:/usr/local/cargo/registry
      - rust-toolchain:/usr/local/rustup
      - target-cache:/usr/src/app/target

    command: sleep infinity

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
      - DATABASE_URL=postgresql://dev_user:dev_password@db:5432/document_automation_dev
      - SQLX_OFFLINE=true
      - CARGO_HOME=/usr/local/cargo
      - RUSTUP_HOME=/usr/local/rustup

    user: rust

volumes:
  cargo-cache:
  rust-toolchain:
  target-cache:


