version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock

    # Add necessary capabilities for Docker
    privileged: true

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
