version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
        consistency: cached
      - vscode-extensions:/home/vscode/.vscode-server/extensions
      - vscode-extensions-insiders:/home/vscode/.vscode-server-insiders/extensions
    command: sleep infinity
    user: vscode
    environment:
      - RUST_BACKTRACE=1
    init: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  vscode-extensions:
  vscode-extensions-insiders:
