[server]
port = 8080
host = "0.0.0.0"

[database]
url = "postgres://dev_user:dev_password@localhost:5432/document_automation_dev"
max_connections = 5

[security]
jwt_secret = "development_secret_key"
jwt_expiration = 3600                 # 1 hour

[storage]
type = "local"
path = "data/documents"

[processing]
max_file_size = 10485760                      # 10MB
allowed_types = ["pdf", "jpg", "png", "tiff"]
ocr_enabled = true
ocr_languages = ["eng"]
