[package]
name = "lotabots-common"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
jsonwebtoken = "8.1"
uuid = { version = "1.0", features = ["v4"] }
validator = "0.14"
prometheus = "0.13"
