apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: cloud-strategy
  labels:
    app: example-app
    environment: ${ENVIRONMENT}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
        environment: ${ENVIRONMENT}
    spec:
      containers:
      - name: example-app
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: ENVIRONMENT
          value: ${ENVIRONMENT}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: example-app 