apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-app
  namespace: cloud-strategy
  labels:
    app: example-app
    environment: ${ENVIRONMENT}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-app
  namespace: cloud-strategy
  labels:
    app: example-app
    environment: ${ENVIRONMENT}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-app
  namespace: cloud-strategy
  labels:
    app: example-app
    environment: ${ENVIRONMENT}
subjects:
- kind: ServiceAccount
  name: example-app
  namespace: cloud-strategy
roleRef:
  kind: Role
  name: example-app
  apiGroup: rbac.authorization.k8s.io 