server:
  ha:
    enabled: true
    replicas: 3
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "raft" {
        path = "/vault/data"
        node_id = "${POD_NAME}"
      }
      service_registration "kubernetes" {}
      
  dataStorage:
    size: 10Gi
    storageClass: "managed-premium"
    
  auditStorage:
    enabled: true
    size: 10Gi
    
  serviceAccount:
    create: true
    annotations:
      kubernetes.io/service-account-name: vault
    
  extraEnvironmentVars:
    VAULT_ADDR: "http://vault.lotabots.svc:8200"
    VAULT_API_ADDR: "http://vault.lotabots.svc:8200"
    VAULT_CLUSTER_ADDR: "http://vault.lotabots.svc:8201"
    
ui:
  enabled: true
  serviceType: ClusterIP
  
injector:
  enabled: true
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m" 