apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: lotabots
  labels:
    app: lotabots
    component: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lotabots
      component: api-gateway
  template:
    metadata:
      labels:
        app: lotabots
        component: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ghcr.io/lotabots/api_gateway:IMAGE_TAG
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: lotabots-config
        - secretRef:
            name: lotabots-secrets
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: ghcr-secret 