apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: lotabots
  labels:
    app: lotabots
    component: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: lotabots
    component: api-gateway 