apiVersion: v1
kind: Secret
metadata:
  name: lotabots-secrets
  namespace: lotabots
type: Opaque
stringData:
  # These are placeholder values that should be replaced in overlays
  NVIDIA_ATTESTATION_API_KEY: "placeholder"
  WANDB_API_KEY: "placeholder"
  MLFLOW_TRACKING_TOKEN: "placeholder"
  JWT_SECRET_KEY: "placeholder"
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/lotabots" 