[package]
name = "api_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
prometheus = { workspace = true }
lazy_static = "1.4"
reqwest = { workspace = true }
futures-util = { workspace = true }
