[server]
host = "0.0.0.0"
port = 8080

[database]
url = "postgres://postgres:postgres@localhost:5432/document_automation"

[storage]
provider = "local"
base_path = "./uploads"

[security]
jwt_secret = "your-secret-key-here"
token_expiry = 86400                # 24 hours in seconds

[logging]
level = "debug"
format = "json"
