name: Auth Service Tests

on:
  push:
    paths:
      - 'services/auth/**'
      - '.github/workflows/auth-tests.yml'
  pull_request:
    paths:
      - 'services/auth/**'
      - '.github/workflows/auth-tests.yml'

env:
  CARGO_TERM_COLOR: always
  TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/lotabots_test
  JWT_SECRET: test_secret_for_ci
  RUSTFLAGS: "-Cinstrument-coverage"
  LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lotabots_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy, llvm-tools-preview

      - name: Install cargo-tarpaulin
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: latest
          use-tool-cache: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            services/auth/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('services/auth/Cargo.lock') }}

      - name: Check formatting
        working-directory: services/auth
        run: cargo fmt -- --check

      - name: Run clippy
        working-directory: services/auth
        run: cargo clippy -- -D warnings

      - name: Run tests with coverage
        working-directory: services/auth
        run: |
          cargo tarpaulin --verbose --workspace --timeout 120 --out Xml --out Html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: services/auth/cobertura.xml
          fail_ci_if_error: true
          verbose: true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: services/auth/tarpaulin-report.html
