[server]
host = "0.0.0.0"
port = 8082

[nats]
url = "nats://localhost:4222"

[metrics]
enabled = true
path = "/metrics"

[logging]
level = "info"
format = "json"

[security]
jwt_key = "${JWT_KEY}"
token_expiry = 86400                # 24 hours in seconds

[agents]
heartbeat_interval = 30 # seconds
timeout = 60            # seconds
